CREATE DATABASE MLP_336

USE MLP_336;
CREATE TABLE MENU_2(FOOD_ID INT PRIMARY KEY ,FOOD_NAME VARCHAR(10), PRICE INT , DESC_FOOD VARCHAR(10) )

CREATE TABLE CUSTOMER(CUST_ID INT PRIMARY KEY ,CUST_NAME VARCHAR(10), CUST_ADDER VARCHAR(20) )
CREATE TABLE VENDOR(VEND_ID INT PRIMARY KEY ,VEND_ADDER VARCHAR(20) ,VEND_NAME VARCHAR(20))
CREATE TABLE ORDER_1(ORDE_ID INT UNIQUE , CUST_ID INT  , VEND_ID INT , FOOD_ID INT, CONSTRAINT CUSTID FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID), CONSTRAINT VENDID FOREIGN KEY (VEND_ID) REFERENCES VENDOR(VEND_ID), CONSTRAINT FOODID FOREIGN KEY (FOOD_ID) REFERENCES MENU_2(FOOD_ID))